# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js App Deploy

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: echo 'Ejecutando deploy job en el roger runner de aws ec2'